import {Component, Input, OnInit} from '@angular/core';
import {RecipesService} from '../../services/recipes.service';
import {Recipe} from '../../models/recipe';
import {Observable} from 'rxjs/Rx';
import {Subject} from 'rxjs/Subject';
import 'rxjs/add/operator/distinctUntilChanged';
import {FormControl} from '@angular/forms';

@Component({
  selector: 'app-recipe-list',
  templateUrl: './recipe-list.component.html',
  styleUrls: ['./recipe-list.component.css'],
  providers: [RecipesService]
})
export class RecipeListComponent implements OnInit {

  @Input()
    title: string;

  selectedRecipe;
  // recipes: Recipe[];
  //
  // constructor(private  recipesService: RecipesService) { }
  //
  // getRecipes(): void {
  //   this.recipesService.getRecipes()
  //     .then(recipes => this.recipes = recipes);
  // }
  //
  // ngOnInit() {
  //   this.getRecipes();
  // }

  myControl: FormControl;  // control for keywords filter
  filteredKeywords: Observable<string[]>;

  // should be generated by services
  keywords = [
    'cake',
    'chocolate',
    'cheese'
  ];

  // declare two Observable
  total$: Observable<number>;
  items$: Observable<Recipe[]>;

  terms = ''; // terms in the search box
  private searchTermStream = new Subject<string>();

  page = 1; // page starts from 1
  private pageStream = new Subject<number>();

  constructor(protected recipeService: RecipesService) {
    this.title = 'Our Recipes';
    this.myControl = new FormControl();
  }

  ngOnInit() {

    this.filteredKeywords = this.myControl.valueChanges
      .startWith(null)
      .map(val => val ? this.filter(val) : this.keywords.slice());

    const searchSource = this.searchTermStream
      .debounceTime(1000)
      .distinctUntilChanged()
      .map(searchTerm => {
        this.terms = searchTerm;
        return {search: searchTerm, page: 1};
      });

    const pageSource = this.pageStream.map(pageNumber => {
      this.page = pageNumber;
      return {search: this.terms, page: pageNumber};
    });

    const source = Observable.from(pageSource)
      .merge(Observable.from(searchSource))
      .startWith({search: this.terms, page: this.page})
      .switchMap((params: {search: string, page: number}) => {
        return this.recipeService.list(params.search, params.page);
      })
      .share();

    this.total$ = source.pluck('total');
    this.items$ = source.pluck('items');
  }

  search(terms: string) {
    this.searchTermStream.next(terms);
  }

  goToPage(page: number) {
    this.pageStream.next(page);
  }


  // filter keywords
  filter(val: string): string[] {
    return this.keywords.filter(keyword => new RegExp(`^${val}`, 'gi').test(keyword));
  }

}
